default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gravytrain_development

test: &test
  <<: *default
  database: gravytrain_test

production:
  <<: *default
  database: gravytrain_production

cucumber:
  <<: *test